-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
-- Version: 2020.2
-- Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Filter_HW_Filter_horizontal_HW_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    inStream_dout : IN STD_LOGIC_VECTOR (7 downto 0);
    inStream_empty_n : IN STD_LOGIC;
    inStream_read : OUT STD_LOGIC;
    tempStream_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    tempStream_full_n : IN STD_LOGIC;
    tempStream_write : OUT STD_LOGIC );
end;


architecture behav of Filter_HW_Filter_horizontal_HW_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (8 downto 0) := "000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (8 downto 0) := "000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (8 downto 0) := "000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (8 downto 0) := "000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (8 downto 0) := "000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (8 downto 0) := "001000000";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (8 downto 0) := "010000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (8 downto 0) := "100000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv9_1 : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    constant ap_const_lv9_10E : STD_LOGIC_VECTOR (8 downto 0) := "100001110";
    constant ap_const_lv9_1DA : STD_LOGIC_VECTOR (8 downto 0) := "111011010";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv15_62 : STD_LOGIC_VECTOR (14 downto 0) := "000000001100010";

attribute shreg_extract : string;
    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (8 downto 0) := "000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal inStream_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln56_fu_165_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal icmp_ln61_reg_372 : STD_LOGIC_VECTOR (0 downto 0);
    signal tempStream_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal icmp_ln61_reg_372_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal X_reg_84 : STD_LOGIC_VECTOR (8 downto 0);
    signal empty_reg_95 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_67_reg_105 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_68_reg_116 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_69_reg_127 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_70_reg_138 : STD_LOGIC_VECTOR (7 downto 0);
    signal empty_71_reg_149 : STD_LOGIC_VECTOR (7 downto 0);
    signal Y_2_fu_159_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal Y_2_reg_329 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_state2 : BOOLEAN;
    signal tmp_reg_337 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_reg_342 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_3_reg_347 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_4_reg_352 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_5_reg_357 : STD_LOGIC_VECTOR (7 downto 0);
    signal X_1_fu_171_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ap_block_state8_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state9_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state10_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal icmp_ln61_fu_177_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_372_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln61_reg_372_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_reg_376 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp2_i_fu_229_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp2_i_reg_386 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp2_i_reg_386_pp0_iter2_reg : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln74_1_fu_267_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln74_1_reg_392 : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln74_1_reg_392_pp0_iter2_reg : STD_LOGIC_VECTOR (14 downto 0);
    signal add_ln74_1_reg_392_pp0_iter3_reg : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_flush_enable : STD_LOGIC;
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_condition_pp0_exit_iter1_state9 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal Y_reg_73 : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal ap_phi_mux_empty_phi_fu_98_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_empty_67_phi_fu_108_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_empty_68_phi_fu_119_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_empty_69_phi_fu_130_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_empty_70_phi_fu_141_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_phi_mux_empty_71_phi_fu_152_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal tmp_8_cast_i_fu_207_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_cast8_i_fu_203_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp6_i_fu_211_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp1_i_fu_217_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal zext_ln74_1_fu_187_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln64_fu_195_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln74_fu_183_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal zext_ln64_1_fu_199_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp4_i_fu_235_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl_i_fu_245_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_shl_cast_i_fu_253_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp4_cast14_i_fu_241_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp5_i_fu_257_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal sext_ln74_fu_263_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp1_i_cast_fu_225_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_shl1_i_fu_273_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal p_shl2_i_fu_284_p3 : STD_LOGIC_VECTOR (9 downto 0);
    signal p_shl1_cast_i_fu_280_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal p_shl2_cast_i_fu_291_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln74_1_fu_301_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_320_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal Sum_fu_304_p2 : STD_LOGIC_VECTOR (15 downto 0);
    attribute use_dsp48 : string;
    attribute use_dsp48 of Sum_fu_304_p2 : signal is "no";
    signal grp_fu_320_p0 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_320_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_320_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_fu_320_ce : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (8 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal grp_fu_320_p00 : STD_LOGIC_VECTOR (14 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component Filter_HW_mac_muladd_8ns_8ns_16ns_16_4_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (7 downto 0);
        din2 : IN STD_LOGIC_VECTOR (15 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    mac_muladd_8ns_8ns_16ns_16_4_1_U10 : component Filter_HW_mac_muladd_8ns_8ns_16ns_16_4_1
    generic map (
        ID => 1,
        NUM_STAGE => 4,
        din0_WIDTH => 8,
        din1_WIDTH => 8,
        din2_WIDTH => 16,
        dout_WIDTH => 16)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => grp_fu_320_p0,
        din1 => grp_fu_320_p1,
        din2 => grp_fu_320_p2,
        ce => grp_fu_320_ce,
        dout => grp_fu_320_p3);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((icmp_ln56_fu_165_p2 = ap_const_lv1_0) and (inStream_empty_n = ap_const_logic_0))) and (icmp_ln56_fu_165_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_pp0_flush_enable)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter1_state9)) then 
                        ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter0;
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                elsif (((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    X_reg_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln61_fu_177_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                X_reg_84 <= X_1_fu_171_p2;
            elsif (((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                X_reg_84 <= ap_const_lv9_0;
            end if; 
        end if;
    end process;

    Y_reg_73_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
                Y_reg_73 <= Y_2_reg_329;
            elsif ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                Y_reg_73 <= ap_const_lv9_0;
            end if; 
        end if;
    end process;

    empty_67_reg_105_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln61_reg_372_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                empty_67_reg_105 <= empty_reg_95;
            elsif (((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                empty_67_reg_105 <= tmp_5_reg_357;
            end if; 
        end if;
    end process;

    empty_68_reg_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln61_reg_372_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                empty_68_reg_116 <= empty_67_reg_105;
            elsif (((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                empty_68_reg_116 <= tmp_4_reg_352;
            end if; 
        end if;
    end process;

    empty_69_reg_127_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln61_reg_372_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                empty_69_reg_127 <= empty_68_reg_116;
            elsif (((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                empty_69_reg_127 <= tmp_3_reg_347;
            end if; 
        end if;
    end process;

    empty_70_reg_138_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln61_reg_372_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                empty_70_reg_138 <= empty_69_reg_127;
            elsif (((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                empty_70_reg_138 <= tmp_2_reg_342;
            end if; 
        end if;
    end process;

    empty_71_reg_149_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln61_reg_372_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                empty_71_reg_149 <= empty_70_reg_138;
            elsif (((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                empty_71_reg_149 <= tmp_reg_337;
            end if; 
        end if;
    end process;

    empty_reg_95_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln61_reg_372_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                empty_reg_95 <= tmp_7_reg_376;
            elsif (((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                empty_reg_95 <= inStream_dout;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((icmp_ln56_fu_165_p2 = ap_const_lv1_0) and (inStream_empty_n = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                Y_2_reg_329 <= Y_2_fu_159_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln61_reg_372 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                add_ln74_1_reg_392 <= add_ln74_1_fu_267_p2;
                tmp2_i_reg_386 <= tmp2_i_fu_229_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                add_ln74_1_reg_392_pp0_iter2_reg <= add_ln74_1_reg_392;
                add_ln74_1_reg_392_pp0_iter3_reg <= add_ln74_1_reg_392_pp0_iter2_reg;
                icmp_ln61_reg_372_pp0_iter2_reg <= icmp_ln61_reg_372_pp0_iter1_reg;
                icmp_ln61_reg_372_pp0_iter3_reg <= icmp_ln61_reg_372_pp0_iter2_reg;
                tmp2_i_reg_386_pp0_iter2_reg <= tmp2_i_reg_386;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                icmp_ln61_reg_372 <= icmp_ln61_fu_177_p2;
                icmp_ln61_reg_372_pp0_iter1_reg <= icmp_ln61_reg_372;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                tmp_2_reg_342 <= inStream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                tmp_3_reg_347 <= inStream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                tmp_4_reg_352 <= inStream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                tmp_5_reg_357 <= inStream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln61_reg_372 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_7_reg_376 <= inStream_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln56_fu_165_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                tmp_reg_337 <= inStream_dout;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, inStream_empty_n, ap_CS_fsm_state2, icmp_ln56_fu_165_p2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((icmp_ln56_fu_165_p2 = ap_const_lv1_0) and (inStream_empty_n = ap_const_logic_0))) and (icmp_ln56_fu_165_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif ((not(((icmp_ln56_fu_165_p2 = ap_const_lv1_0) and (inStream_empty_n = ap_const_logic_0))) and (icmp_ln56_fu_165_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if (((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if (((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if (((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                if (((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) and not(((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) or ((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone)))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXX";
        end case;
    end process;
    Sum_fu_304_p2 <= std_logic_vector(signed(sext_ln74_1_fu_301_p1) + signed(grp_fu_320_p3));
    X_1_fu_171_p2 <= std_logic_vector(unsigned(X_reg_84) + unsigned(ap_const_lv9_1));
    Y_2_fu_159_p2 <= std_logic_vector(unsigned(Y_reg_73) + unsigned(ap_const_lv9_1));
    add_ln74_1_fu_267_p2 <= std_logic_vector(signed(sext_ln74_fu_263_p1) + signed(tmp1_i_cast_fu_225_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(7);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state13 <= ap_CS_fsm(8);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(inStream_empty_n, tempStream_full_n, ap_enable_reg_pp0_iter1, icmp_ln61_reg_372, ap_enable_reg_pp0_iter4, icmp_ln61_reg_372_pp0_iter3_reg)
    begin
                ap_block_pp0_stage0_01001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (inStream_empty_n = ap_const_logic_0) and (icmp_ln61_reg_372 = ap_const_lv1_0)) or ((tempStream_full_n = ap_const_logic_0) and (icmp_ln61_reg_372_pp0_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(inStream_empty_n, tempStream_full_n, ap_enable_reg_pp0_iter1, icmp_ln61_reg_372, ap_enable_reg_pp0_iter4, icmp_ln61_reg_372_pp0_iter3_reg)
    begin
                ap_block_pp0_stage0_11001 <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (inStream_empty_n = ap_const_logic_0) and (icmp_ln61_reg_372 = ap_const_lv1_0)) or ((tempStream_full_n = ap_const_logic_0) and (icmp_ln61_reg_372_pp0_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(inStream_empty_n, tempStream_full_n, ap_enable_reg_pp0_iter1, icmp_ln61_reg_372, ap_enable_reg_pp0_iter4, icmp_ln61_reg_372_pp0_iter3_reg)
    begin
                ap_block_pp0_stage0_subdone <= (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (inStream_empty_n = ap_const_logic_0) and (icmp_ln61_reg_372 = ap_const_lv1_0)) or ((tempStream_full_n = ap_const_logic_0) and (icmp_ln61_reg_372_pp0_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)));
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_done_reg = ap_const_logic_1) or (real_start = ap_const_logic_0));
    end process;

        ap_block_state10_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state12_pp0_stage0_iter4_assign_proc : process(tempStream_full_n, icmp_ln61_reg_372_pp0_iter3_reg)
    begin
                ap_block_state12_pp0_stage0_iter4 <= ((tempStream_full_n = ap_const_logic_0) and (icmp_ln61_reg_372_pp0_iter3_reg = ap_const_lv1_0));
    end process;


    ap_block_state2_assign_proc : process(inStream_empty_n, icmp_ln56_fu_165_p2)
    begin
                ap_block_state2 <= ((icmp_ln56_fu_165_p2 = ap_const_lv1_0) and (inStream_empty_n = ap_const_logic_0));
    end process;

        ap_block_state8_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state9_pp0_stage0_iter1_assign_proc : process(inStream_empty_n, icmp_ln61_reg_372)
    begin
                ap_block_state9_pp0_stage0_iter1 <= ((inStream_empty_n = ap_const_logic_0) and (icmp_ln61_reg_372 = ap_const_lv1_0));
    end process;


    ap_condition_pp0_exit_iter1_state9_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_condition_pp0_exit_iter1_state9 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter1_state9 <= ap_const_logic_0;
        end if; 
    end process;


    ap_condition_pp0_flush_enable_assign_proc : process(ap_CS_fsm_pp0_stage0, icmp_ln61_fu_177_p2, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln61_fu_177_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone))) then 
            ap_condition_pp0_flush_enable <= ap_const_logic_1;
        else 
            ap_condition_pp0_flush_enable <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, inStream_empty_n, ap_CS_fsm_state2, icmp_ln56_fu_165_p2)
    begin
        if ((not(((icmp_ln56_fu_165_p2 = ap_const_lv1_0) and (inStream_empty_n = ap_const_logic_0))) and (icmp_ln56_fu_165_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (real_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_empty_67_phi_fu_108_p4_assign_proc : process(ap_block_pp0_stage0, empty_reg_95, empty_67_reg_105, icmp_ln61_reg_372_pp0_iter1_reg, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln61_reg_372_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_empty_67_phi_fu_108_p4 <= empty_reg_95;
        else 
            ap_phi_mux_empty_67_phi_fu_108_p4 <= empty_67_reg_105;
        end if; 
    end process;


    ap_phi_mux_empty_68_phi_fu_119_p4_assign_proc : process(ap_block_pp0_stage0, empty_67_reg_105, empty_68_reg_116, icmp_ln61_reg_372_pp0_iter1_reg, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln61_reg_372_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_empty_68_phi_fu_119_p4 <= empty_67_reg_105;
        else 
            ap_phi_mux_empty_68_phi_fu_119_p4 <= empty_68_reg_116;
        end if; 
    end process;


    ap_phi_mux_empty_69_phi_fu_130_p4_assign_proc : process(ap_block_pp0_stage0, empty_68_reg_116, empty_69_reg_127, icmp_ln61_reg_372_pp0_iter1_reg, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln61_reg_372_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_empty_69_phi_fu_130_p4 <= empty_68_reg_116;
        else 
            ap_phi_mux_empty_69_phi_fu_130_p4 <= empty_69_reg_127;
        end if; 
    end process;


    ap_phi_mux_empty_70_phi_fu_141_p4_assign_proc : process(ap_block_pp0_stage0, empty_69_reg_127, empty_70_reg_138, icmp_ln61_reg_372_pp0_iter1_reg, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln61_reg_372_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_empty_70_phi_fu_141_p4 <= empty_69_reg_127;
        else 
            ap_phi_mux_empty_70_phi_fu_141_p4 <= empty_70_reg_138;
        end if; 
    end process;


    ap_phi_mux_empty_71_phi_fu_152_p4_assign_proc : process(ap_block_pp0_stage0, empty_70_reg_138, empty_71_reg_149, icmp_ln61_reg_372_pp0_iter1_reg, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln61_reg_372_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_empty_71_phi_fu_152_p4 <= empty_70_reg_138;
        else 
            ap_phi_mux_empty_71_phi_fu_152_p4 <= empty_71_reg_149;
        end if; 
    end process;


    ap_phi_mux_empty_phi_fu_98_p4_assign_proc : process(ap_block_pp0_stage0, empty_reg_95, icmp_ln61_reg_372_pp0_iter1_reg, tmp_7_reg_376, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (icmp_ln61_reg_372_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            ap_phi_mux_empty_phi_fu_98_p4 <= tmp_7_reg_376;
        else 
            ap_phi_mux_empty_phi_fu_98_p4 <= empty_reg_95;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    grp_fu_320_ce_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            grp_fu_320_ce <= ap_const_logic_1;
        else 
            grp_fu_320_ce <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_320_p0 <= grp_fu_320_p00(8 - 1 downto 0);
    grp_fu_320_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_empty_68_phi_fu_119_p4),15));
    grp_fu_320_p1 <= ap_const_lv15_62(8 - 1 downto 0);
    grp_fu_320_p2 <= std_logic_vector(unsigned(p_shl1_cast_i_fu_280_p1) - unsigned(p_shl2_cast_i_fu_291_p1));
    icmp_ln56_fu_165_p2 <= "1" when (Y_reg_73 = ap_const_lv9_10E) else "0";
    icmp_ln61_fu_177_p2 <= "1" when (X_reg_84 = ap_const_lv9_1DA) else "0";

    inStream_blk_n_assign_proc : process(inStream_empty_n, ap_CS_fsm_state2, icmp_ln56_fu_165_p2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0, icmp_ln61_reg_372)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln61_reg_372 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0)) or ((icmp_ln56_fu_165_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            inStream_blk_n <= inStream_empty_n;
        else 
            inStream_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    inStream_read_assign_proc : process(inStream_empty_n, ap_CS_fsm_state2, icmp_ln56_fu_165_p2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, icmp_ln61_reg_372, ap_block_pp0_stage0_11001)
    begin
        if ((((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (icmp_ln61_reg_372 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state7)) or ((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6)) or ((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5)) or ((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((inStream_empty_n = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or (not(((icmp_ln56_fu_165_p2 = ap_const_lv1_0) and (inStream_empty_n = ap_const_logic_0))) and (icmp_ln56_fu_165_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            inStream_read <= ap_const_logic_1;
        else 
            inStream_read <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(inStream_empty_n, ap_CS_fsm_state2, icmp_ln56_fu_165_p2)
    begin
        if ((not(((icmp_ln56_fu_165_p2 = ap_const_lv1_0) and (inStream_empty_n = ap_const_logic_0))) and (icmp_ln56_fu_165_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    p_cast8_i_fu_203_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_empty_71_phi_fu_152_p4),9));
    p_shl1_cast_i_fu_280_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl1_i_fu_273_p3),16));
    p_shl1_i_fu_273_p3 <= (tmp2_i_reg_386_pp0_iter2_reg & ap_const_lv6_0);
    p_shl2_cast_i_fu_291_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl2_i_fu_284_p3),16));
    p_shl2_i_fu_284_p3 <= (tmp2_i_reg_386_pp0_iter2_reg & ap_const_lv1_0);
    p_shl_cast_i_fu_253_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(p_shl_i_fu_245_p3),14));
    p_shl_i_fu_245_p3 <= (tmp4_i_fu_235_p2 & ap_const_lv4_0);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

        sext_ln74_1_fu_301_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln74_1_reg_392_pp0_iter3_reg),16));

        sext_ln74_fu_263_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp5_i_fu_257_p2),15));

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;


    tempStream_blk_n_assign_proc : process(tempStream_full_n, ap_block_pp0_stage0, ap_enable_reg_pp0_iter4, icmp_ln61_reg_372_pp0_iter3_reg)
    begin
        if (((icmp_ln61_reg_372_pp0_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            tempStream_blk_n <= tempStream_full_n;
        else 
            tempStream_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    tempStream_din <= Sum_fu_304_p2(15 downto 8);

    tempStream_write_assign_proc : process(ap_enable_reg_pp0_iter4, icmp_ln61_reg_372_pp0_iter3_reg, ap_block_pp0_stage0_11001)
    begin
        if (((icmp_ln61_reg_372_pp0_iter3_reg = ap_const_lv1_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            tempStream_write <= ap_const_logic_1;
        else 
            tempStream_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp1_i_cast_fu_225_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp1_i_fu_217_p3),15));
    tmp1_i_fu_217_p3 <= (tmp6_i_fu_211_p2 & ap_const_lv1_0);
    tmp2_i_fu_229_p2 <= std_logic_vector(unsigned(zext_ln74_1_fu_187_p1) + unsigned(zext_ln64_fu_195_p1));
    tmp4_cast14_i_fu_241_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp4_i_fu_235_p2),14));
    tmp4_i_fu_235_p2 <= std_logic_vector(unsigned(zext_ln74_fu_183_p1) + unsigned(zext_ln64_1_fu_199_p1));
    tmp5_i_fu_257_p2 <= std_logic_vector(unsigned(p_shl_cast_i_fu_253_p1) - unsigned(tmp4_cast14_i_fu_241_p1));
    tmp6_i_fu_211_p2 <= std_logic_vector(unsigned(tmp_8_cast_i_fu_207_p1) + unsigned(p_cast8_i_fu_203_p1));
    tmp_8_cast_i_fu_207_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(inStream_dout),9));
    zext_ln64_1_fu_199_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_empty_phi_fu_98_p4),9));
    zext_ln64_fu_195_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_empty_67_phi_fu_108_p4),9));
    zext_ln74_1_fu_187_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_empty_69_phi_fu_130_p4),9));
    zext_ln74_fu_183_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_mux_empty_70_phi_fu_141_p4),9));
end behav;
