// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Filter_HW_Filter_HW,hls_ip_2020_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu3eg-sbva484-1-i,HLS_INPUT_CLOCK=6.667000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=4.866910,HLS_SYN_LAT=310255,HLS_SYN_TPT=170372,HLS_SYN_MEM=11,HLS_SYN_DSP=0,HLS_SYN_FF=7299,HLS_SYN_LUT=42426,HLS_VERSION=2020_2}" *)

module Filter_HW (
        s_axi_control_AWVALID,
        s_axi_control_AWREADY,
        s_axi_control_AWADDR,
        s_axi_control_WVALID,
        s_axi_control_WREADY,
        s_axi_control_WDATA,
        s_axi_control_WSTRB,
        s_axi_control_ARVALID,
        s_axi_control_ARREADY,
        s_axi_control_ARADDR,
        s_axi_control_RVALID,
        s_axi_control_RREADY,
        s_axi_control_RDATA,
        s_axi_control_RRESP,
        s_axi_control_BVALID,
        s_axi_control_BREADY,
        s_axi_control_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        m_axi_aximm1_AWVALID,
        m_axi_aximm1_AWREADY,
        m_axi_aximm1_AWADDR,
        m_axi_aximm1_AWID,
        m_axi_aximm1_AWLEN,
        m_axi_aximm1_AWSIZE,
        m_axi_aximm1_AWBURST,
        m_axi_aximm1_AWLOCK,
        m_axi_aximm1_AWCACHE,
        m_axi_aximm1_AWPROT,
        m_axi_aximm1_AWQOS,
        m_axi_aximm1_AWREGION,
        m_axi_aximm1_AWUSER,
        m_axi_aximm1_WVALID,
        m_axi_aximm1_WREADY,
        m_axi_aximm1_WDATA,
        m_axi_aximm1_WSTRB,
        m_axi_aximm1_WLAST,
        m_axi_aximm1_WID,
        m_axi_aximm1_WUSER,
        m_axi_aximm1_ARVALID,
        m_axi_aximm1_ARREADY,
        m_axi_aximm1_ARADDR,
        m_axi_aximm1_ARID,
        m_axi_aximm1_ARLEN,
        m_axi_aximm1_ARSIZE,
        m_axi_aximm1_ARBURST,
        m_axi_aximm1_ARLOCK,
        m_axi_aximm1_ARCACHE,
        m_axi_aximm1_ARPROT,
        m_axi_aximm1_ARQOS,
        m_axi_aximm1_ARREGION,
        m_axi_aximm1_ARUSER,
        m_axi_aximm1_RVALID,
        m_axi_aximm1_RREADY,
        m_axi_aximm1_RDATA,
        m_axi_aximm1_RLAST,
        m_axi_aximm1_RID,
        m_axi_aximm1_RUSER,
        m_axi_aximm1_RRESP,
        m_axi_aximm1_BVALID,
        m_axi_aximm1_BREADY,
        m_axi_aximm1_BRESP,
        m_axi_aximm1_BID,
        m_axi_aximm1_BUSER,
        m_axi_aximm2_AWVALID,
        m_axi_aximm2_AWREADY,
        m_axi_aximm2_AWADDR,
        m_axi_aximm2_AWID,
        m_axi_aximm2_AWLEN,
        m_axi_aximm2_AWSIZE,
        m_axi_aximm2_AWBURST,
        m_axi_aximm2_AWLOCK,
        m_axi_aximm2_AWCACHE,
        m_axi_aximm2_AWPROT,
        m_axi_aximm2_AWQOS,
        m_axi_aximm2_AWREGION,
        m_axi_aximm2_AWUSER,
        m_axi_aximm2_WVALID,
        m_axi_aximm2_WREADY,
        m_axi_aximm2_WDATA,
        m_axi_aximm2_WSTRB,
        m_axi_aximm2_WLAST,
        m_axi_aximm2_WID,
        m_axi_aximm2_WUSER,
        m_axi_aximm2_ARVALID,
        m_axi_aximm2_ARREADY,
        m_axi_aximm2_ARADDR,
        m_axi_aximm2_ARID,
        m_axi_aximm2_ARLEN,
        m_axi_aximm2_ARSIZE,
        m_axi_aximm2_ARBURST,
        m_axi_aximm2_ARLOCK,
        m_axi_aximm2_ARCACHE,
        m_axi_aximm2_ARPROT,
        m_axi_aximm2_ARQOS,
        m_axi_aximm2_ARREGION,
        m_axi_aximm2_ARUSER,
        m_axi_aximm2_RVALID,
        m_axi_aximm2_RREADY,
        m_axi_aximm2_RDATA,
        m_axi_aximm2_RLAST,
        m_axi_aximm2_RID,
        m_axi_aximm2_RUSER,
        m_axi_aximm2_RRESP,
        m_axi_aximm2_BVALID,
        m_axi_aximm2_BREADY,
        m_axi_aximm2_BRESP,
        m_axi_aximm2_BID,
        m_axi_aximm2_BUSER
);

parameter    C_S_AXI_CONTROL_DATA_WIDTH = 32;
parameter    C_S_AXI_CONTROL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_ADDR_WIDTH = 32;
parameter    C_M_AXI_AXIMM1_ID_WIDTH = 1;
parameter    C_M_AXI_AXIMM1_ADDR_WIDTH = 64;
parameter    C_M_AXI_AXIMM1_DATA_WIDTH = 32;
parameter    C_M_AXI_AXIMM1_AWUSER_WIDTH = 1;
parameter    C_M_AXI_AXIMM1_ARUSER_WIDTH = 1;
parameter    C_M_AXI_AXIMM1_WUSER_WIDTH = 1;
parameter    C_M_AXI_AXIMM1_RUSER_WIDTH = 1;
parameter    C_M_AXI_AXIMM1_BUSER_WIDTH = 1;
parameter    C_M_AXI_AXIMM1_USER_VALUE = 0;
parameter    C_M_AXI_AXIMM1_PROT_VALUE = 0;
parameter    C_M_AXI_AXIMM1_CACHE_VALUE = 3;
parameter    C_M_AXI_ID_WIDTH = 1;
parameter    C_M_AXI_ADDR_WIDTH = 64;
parameter    C_M_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_AWUSER_WIDTH = 1;
parameter    C_M_AXI_ARUSER_WIDTH = 1;
parameter    C_M_AXI_WUSER_WIDTH = 1;
parameter    C_M_AXI_RUSER_WIDTH = 1;
parameter    C_M_AXI_BUSER_WIDTH = 1;
parameter    C_M_AXI_AXIMM2_ID_WIDTH = 1;
parameter    C_M_AXI_AXIMM2_ADDR_WIDTH = 64;
parameter    C_M_AXI_AXIMM2_DATA_WIDTH = 32;
parameter    C_M_AXI_AXIMM2_AWUSER_WIDTH = 1;
parameter    C_M_AXI_AXIMM2_ARUSER_WIDTH = 1;
parameter    C_M_AXI_AXIMM2_WUSER_WIDTH = 1;
parameter    C_M_AXI_AXIMM2_RUSER_WIDTH = 1;
parameter    C_M_AXI_AXIMM2_BUSER_WIDTH = 1;
parameter    C_M_AXI_AXIMM2_USER_VALUE = 0;
parameter    C_M_AXI_AXIMM2_PROT_VALUE = 0;
parameter    C_M_AXI_AXIMM2_CACHE_VALUE = 3;

parameter C_S_AXI_CONTROL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_AXIMM1_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_AXIMM2_WSTRB_WIDTH = (32 / 8);

input   s_axi_control_AWVALID;
output   s_axi_control_AWREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_AWADDR;
input   s_axi_control_WVALID;
output   s_axi_control_WREADY;
input  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_WDATA;
input  [C_S_AXI_CONTROL_WSTRB_WIDTH - 1:0] s_axi_control_WSTRB;
input   s_axi_control_ARVALID;
output   s_axi_control_ARREADY;
input  [C_S_AXI_CONTROL_ADDR_WIDTH - 1:0] s_axi_control_ARADDR;
output   s_axi_control_RVALID;
input   s_axi_control_RREADY;
output  [C_S_AXI_CONTROL_DATA_WIDTH - 1:0] s_axi_control_RDATA;
output  [1:0] s_axi_control_RRESP;
output   s_axi_control_BVALID;
input   s_axi_control_BREADY;
output  [1:0] s_axi_control_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
output   m_axi_aximm1_AWVALID;
input   m_axi_aximm1_AWREADY;
output  [C_M_AXI_AXIMM1_ADDR_WIDTH - 1:0] m_axi_aximm1_AWADDR;
output  [C_M_AXI_AXIMM1_ID_WIDTH - 1:0] m_axi_aximm1_AWID;
output  [7:0] m_axi_aximm1_AWLEN;
output  [2:0] m_axi_aximm1_AWSIZE;
output  [1:0] m_axi_aximm1_AWBURST;
output  [1:0] m_axi_aximm1_AWLOCK;
output  [3:0] m_axi_aximm1_AWCACHE;
output  [2:0] m_axi_aximm1_AWPROT;
output  [3:0] m_axi_aximm1_AWQOS;
output  [3:0] m_axi_aximm1_AWREGION;
output  [C_M_AXI_AXIMM1_AWUSER_WIDTH - 1:0] m_axi_aximm1_AWUSER;
output   m_axi_aximm1_WVALID;
input   m_axi_aximm1_WREADY;
output  [C_M_AXI_AXIMM1_DATA_WIDTH - 1:0] m_axi_aximm1_WDATA;
output  [C_M_AXI_AXIMM1_WSTRB_WIDTH - 1:0] m_axi_aximm1_WSTRB;
output   m_axi_aximm1_WLAST;
output  [C_M_AXI_AXIMM1_ID_WIDTH - 1:0] m_axi_aximm1_WID;
output  [C_M_AXI_AXIMM1_WUSER_WIDTH - 1:0] m_axi_aximm1_WUSER;
output   m_axi_aximm1_ARVALID;
input   m_axi_aximm1_ARREADY;
output  [C_M_AXI_AXIMM1_ADDR_WIDTH - 1:0] m_axi_aximm1_ARADDR;
output  [C_M_AXI_AXIMM1_ID_WIDTH - 1:0] m_axi_aximm1_ARID;
output  [7:0] m_axi_aximm1_ARLEN;
output  [2:0] m_axi_aximm1_ARSIZE;
output  [1:0] m_axi_aximm1_ARBURST;
output  [1:0] m_axi_aximm1_ARLOCK;
output  [3:0] m_axi_aximm1_ARCACHE;
output  [2:0] m_axi_aximm1_ARPROT;
output  [3:0] m_axi_aximm1_ARQOS;
output  [3:0] m_axi_aximm1_ARREGION;
output  [C_M_AXI_AXIMM1_ARUSER_WIDTH - 1:0] m_axi_aximm1_ARUSER;
input   m_axi_aximm1_RVALID;
output   m_axi_aximm1_RREADY;
input  [C_M_AXI_AXIMM1_DATA_WIDTH - 1:0] m_axi_aximm1_RDATA;
input   m_axi_aximm1_RLAST;
input  [C_M_AXI_AXIMM1_ID_WIDTH - 1:0] m_axi_aximm1_RID;
input  [C_M_AXI_AXIMM1_RUSER_WIDTH - 1:0] m_axi_aximm1_RUSER;
input  [1:0] m_axi_aximm1_RRESP;
input   m_axi_aximm1_BVALID;
output   m_axi_aximm1_BREADY;
input  [1:0] m_axi_aximm1_BRESP;
input  [C_M_AXI_AXIMM1_ID_WIDTH - 1:0] m_axi_aximm1_BID;
input  [C_M_AXI_AXIMM1_BUSER_WIDTH - 1:0] m_axi_aximm1_BUSER;
output   m_axi_aximm2_AWVALID;
input   m_axi_aximm2_AWREADY;
output  [C_M_AXI_AXIMM2_ADDR_WIDTH - 1:0] m_axi_aximm2_AWADDR;
output  [C_M_AXI_AXIMM2_ID_WIDTH - 1:0] m_axi_aximm2_AWID;
output  [7:0] m_axi_aximm2_AWLEN;
output  [2:0] m_axi_aximm2_AWSIZE;
output  [1:0] m_axi_aximm2_AWBURST;
output  [1:0] m_axi_aximm2_AWLOCK;
output  [3:0] m_axi_aximm2_AWCACHE;
output  [2:0] m_axi_aximm2_AWPROT;
output  [3:0] m_axi_aximm2_AWQOS;
output  [3:0] m_axi_aximm2_AWREGION;
output  [C_M_AXI_AXIMM2_AWUSER_WIDTH - 1:0] m_axi_aximm2_AWUSER;
output   m_axi_aximm2_WVALID;
input   m_axi_aximm2_WREADY;
output  [C_M_AXI_AXIMM2_DATA_WIDTH - 1:0] m_axi_aximm2_WDATA;
output  [C_M_AXI_AXIMM2_WSTRB_WIDTH - 1:0] m_axi_aximm2_WSTRB;
output   m_axi_aximm2_WLAST;
output  [C_M_AXI_AXIMM2_ID_WIDTH - 1:0] m_axi_aximm2_WID;
output  [C_M_AXI_AXIMM2_WUSER_WIDTH - 1:0] m_axi_aximm2_WUSER;
output   m_axi_aximm2_ARVALID;
input   m_axi_aximm2_ARREADY;
output  [C_M_AXI_AXIMM2_ADDR_WIDTH - 1:0] m_axi_aximm2_ARADDR;
output  [C_M_AXI_AXIMM2_ID_WIDTH - 1:0] m_axi_aximm2_ARID;
output  [7:0] m_axi_aximm2_ARLEN;
output  [2:0] m_axi_aximm2_ARSIZE;
output  [1:0] m_axi_aximm2_ARBURST;
output  [1:0] m_axi_aximm2_ARLOCK;
output  [3:0] m_axi_aximm2_ARCACHE;
output  [2:0] m_axi_aximm2_ARPROT;
output  [3:0] m_axi_aximm2_ARQOS;
output  [3:0] m_axi_aximm2_ARREGION;
output  [C_M_AXI_AXIMM2_ARUSER_WIDTH - 1:0] m_axi_aximm2_ARUSER;
input   m_axi_aximm2_RVALID;
output   m_axi_aximm2_RREADY;
input  [C_M_AXI_AXIMM2_DATA_WIDTH - 1:0] m_axi_aximm2_RDATA;
input   m_axi_aximm2_RLAST;
input  [C_M_AXI_AXIMM2_ID_WIDTH - 1:0] m_axi_aximm2_RID;
input  [C_M_AXI_AXIMM2_RUSER_WIDTH - 1:0] m_axi_aximm2_RUSER;
input  [1:0] m_axi_aximm2_RRESP;
input   m_axi_aximm2_BVALID;
output   m_axi_aximm2_BREADY;
input  [1:0] m_axi_aximm2_BRESP;
input  [C_M_AXI_AXIMM2_ID_WIDTH - 1:0] m_axi_aximm2_BID;
input  [C_M_AXI_AXIMM2_BUSER_WIDTH - 1:0] m_axi_aximm2_BUSER;

(* shreg_extract = "no" *) reg    ap_rst_reg_2;
(* shreg_extract = "no" *) reg    ap_rst_reg_1;
(* shreg_extract = "no" *) reg    ap_rst_n_inv;
wire   [63:0] Input_r;
wire   [63:0] Output_r;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_continue;
wire    ap_idle;
wire    aximm1_AWREADY;
wire    aximm1_WREADY;
wire    aximm1_ARREADY;
wire    aximm1_RVALID;
wire   [15:0] aximm1_RDATA;
wire    aximm1_RLAST;
wire   [0:0] aximm1_RID;
wire   [0:0] aximm1_RUSER;
wire   [1:0] aximm1_RRESP;
wire    aximm1_BVALID;
wire   [1:0] aximm1_BRESP;
wire   [0:0] aximm1_BID;
wire   [0:0] aximm1_BUSER;
wire    aximm2_AWREADY;
wire    aximm2_WREADY;
wire    aximm2_ARREADY;
wire    aximm2_RVALID;
wire   [15:0] aximm2_RDATA;
wire    aximm2_RLAST;
wire   [0:0] aximm2_RID;
wire   [0:0] aximm2_RUSER;
wire   [1:0] aximm2_RRESP;
wire    aximm2_BVALID;
wire   [1:0] aximm2_BRESP;
wire   [0:0] aximm2_BID;
wire   [0:0] aximm2_BUSER;
wire    Filter_horizontal_HW3_U0_ap_start;
wire    Filter_horizontal_HW3_U0_ap_done;
wire    Filter_horizontal_HW3_U0_ap_continue;
wire    Filter_horizontal_HW3_U0_ap_idle;
wire    Filter_horizontal_HW3_U0_ap_ready;
wire    Filter_horizontal_HW3_U0_start_out;
wire    Filter_horizontal_HW3_U0_start_write;
wire    Filter_horizontal_HW3_U0_m_axi_aximm1_AWVALID;
wire   [63:0] Filter_horizontal_HW3_U0_m_axi_aximm1_AWADDR;
wire   [0:0] Filter_horizontal_HW3_U0_m_axi_aximm1_AWID;
wire   [31:0] Filter_horizontal_HW3_U0_m_axi_aximm1_AWLEN;
wire   [2:0] Filter_horizontal_HW3_U0_m_axi_aximm1_AWSIZE;
wire   [1:0] Filter_horizontal_HW3_U0_m_axi_aximm1_AWBURST;
wire   [1:0] Filter_horizontal_HW3_U0_m_axi_aximm1_AWLOCK;
wire   [3:0] Filter_horizontal_HW3_U0_m_axi_aximm1_AWCACHE;
wire   [2:0] Filter_horizontal_HW3_U0_m_axi_aximm1_AWPROT;
wire   [3:0] Filter_horizontal_HW3_U0_m_axi_aximm1_AWQOS;
wire   [3:0] Filter_horizontal_HW3_U0_m_axi_aximm1_AWREGION;
wire   [0:0] Filter_horizontal_HW3_U0_m_axi_aximm1_AWUSER;
wire    Filter_horizontal_HW3_U0_m_axi_aximm1_WVALID;
wire   [15:0] Filter_horizontal_HW3_U0_m_axi_aximm1_WDATA;
wire   [1:0] Filter_horizontal_HW3_U0_m_axi_aximm1_WSTRB;
wire    Filter_horizontal_HW3_U0_m_axi_aximm1_WLAST;
wire   [0:0] Filter_horizontal_HW3_U0_m_axi_aximm1_WID;
wire   [0:0] Filter_horizontal_HW3_U0_m_axi_aximm1_WUSER;
wire    Filter_horizontal_HW3_U0_m_axi_aximm1_ARVALID;
wire   [63:0] Filter_horizontal_HW3_U0_m_axi_aximm1_ARADDR;
wire   [0:0] Filter_horizontal_HW3_U0_m_axi_aximm1_ARID;
wire   [31:0] Filter_horizontal_HW3_U0_m_axi_aximm1_ARLEN;
wire   [2:0] Filter_horizontal_HW3_U0_m_axi_aximm1_ARSIZE;
wire   [1:0] Filter_horizontal_HW3_U0_m_axi_aximm1_ARBURST;
wire   [1:0] Filter_horizontal_HW3_U0_m_axi_aximm1_ARLOCK;
wire   [3:0] Filter_horizontal_HW3_U0_m_axi_aximm1_ARCACHE;
wire   [2:0] Filter_horizontal_HW3_U0_m_axi_aximm1_ARPROT;
wire   [3:0] Filter_horizontal_HW3_U0_m_axi_aximm1_ARQOS;
wire   [3:0] Filter_horizontal_HW3_U0_m_axi_aximm1_ARREGION;
wire   [0:0] Filter_horizontal_HW3_U0_m_axi_aximm1_ARUSER;
wire    Filter_horizontal_HW3_U0_m_axi_aximm1_RREADY;
wire    Filter_horizontal_HW3_U0_m_axi_aximm1_BREADY;
wire   [63:0] Filter_horizontal_HW3_U0_Output_out_din;
wire    Filter_horizontal_HW3_U0_Output_out_write;
wire   [7:0] Filter_horizontal_HW3_U0_tempStream_din;
wire    Filter_horizontal_HW3_U0_tempStream_write;
wire    Filter_vertical_HW_U0_ap_start;
wire    Filter_vertical_HW_U0_ap_done;
wire    Filter_vertical_HW_U0_ap_continue;
wire    Filter_vertical_HW_U0_ap_idle;
wire    Filter_vertical_HW_U0_ap_ready;
wire    Filter_vertical_HW_U0_m_axi_aximm2_AWVALID;
wire   [63:0] Filter_vertical_HW_U0_m_axi_aximm2_AWADDR;
wire   [0:0] Filter_vertical_HW_U0_m_axi_aximm2_AWID;
wire   [31:0] Filter_vertical_HW_U0_m_axi_aximm2_AWLEN;
wire   [2:0] Filter_vertical_HW_U0_m_axi_aximm2_AWSIZE;
wire   [1:0] Filter_vertical_HW_U0_m_axi_aximm2_AWBURST;
wire   [1:0] Filter_vertical_HW_U0_m_axi_aximm2_AWLOCK;
wire   [3:0] Filter_vertical_HW_U0_m_axi_aximm2_AWCACHE;
wire   [2:0] Filter_vertical_HW_U0_m_axi_aximm2_AWPROT;
wire   [3:0] Filter_vertical_HW_U0_m_axi_aximm2_AWQOS;
wire   [3:0] Filter_vertical_HW_U0_m_axi_aximm2_AWREGION;
wire   [0:0] Filter_vertical_HW_U0_m_axi_aximm2_AWUSER;
wire    Filter_vertical_HW_U0_m_axi_aximm2_WVALID;
wire   [15:0] Filter_vertical_HW_U0_m_axi_aximm2_WDATA;
wire   [1:0] Filter_vertical_HW_U0_m_axi_aximm2_WSTRB;
wire    Filter_vertical_HW_U0_m_axi_aximm2_WLAST;
wire   [0:0] Filter_vertical_HW_U0_m_axi_aximm2_WID;
wire   [0:0] Filter_vertical_HW_U0_m_axi_aximm2_WUSER;
wire    Filter_vertical_HW_U0_m_axi_aximm2_ARVALID;
wire   [63:0] Filter_vertical_HW_U0_m_axi_aximm2_ARADDR;
wire   [0:0] Filter_vertical_HW_U0_m_axi_aximm2_ARID;
wire   [31:0] Filter_vertical_HW_U0_m_axi_aximm2_ARLEN;
wire   [2:0] Filter_vertical_HW_U0_m_axi_aximm2_ARSIZE;
wire   [1:0] Filter_vertical_HW_U0_m_axi_aximm2_ARBURST;
wire   [1:0] Filter_vertical_HW_U0_m_axi_aximm2_ARLOCK;
wire   [3:0] Filter_vertical_HW_U0_m_axi_aximm2_ARCACHE;
wire   [2:0] Filter_vertical_HW_U0_m_axi_aximm2_ARPROT;
wire   [3:0] Filter_vertical_HW_U0_m_axi_aximm2_ARQOS;
wire   [3:0] Filter_vertical_HW_U0_m_axi_aximm2_ARREGION;
wire   [0:0] Filter_vertical_HW_U0_m_axi_aximm2_ARUSER;
wire    Filter_vertical_HW_U0_m_axi_aximm2_RREADY;
wire    Filter_vertical_HW_U0_m_axi_aximm2_BREADY;
wire    Filter_vertical_HW_U0_Output_r_read;
wire    Filter_vertical_HW_U0_tempStream_read;
wire    ap_sync_continue;
wire    Output_c_full_n;
wire   [63:0] Output_c_dout;
wire    Output_c_empty_n;
wire    tempStream_full_n;
wire   [7:0] tempStream_dout;
wire    tempStream_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
wire   [0:0] start_for_Filter_vertical_HW_U0_din;
wire    start_for_Filter_vertical_HW_U0_full_n;
wire   [0:0] start_for_Filter_vertical_HW_U0_dout;
wire    start_for_Filter_vertical_HW_U0_empty_n;
wire    Filter_vertical_HW_U0_start_full_n;
wire    Filter_vertical_HW_U0_start_write;

// power-on initialization
initial begin
#0 ap_rst_reg_2 = 1'b1;
#0 ap_rst_reg_1 = 1'b1;
#0 ap_rst_n_inv = 1'b1;
end

Filter_HW_control_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CONTROL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CONTROL_DATA_WIDTH ))
control_s_axi_U(
    .AWVALID(s_axi_control_AWVALID),
    .AWREADY(s_axi_control_AWREADY),
    .AWADDR(s_axi_control_AWADDR),
    .WVALID(s_axi_control_WVALID),
    .WREADY(s_axi_control_WREADY),
    .WDATA(s_axi_control_WDATA),
    .WSTRB(s_axi_control_WSTRB),
    .ARVALID(s_axi_control_ARVALID),
    .ARREADY(s_axi_control_ARREADY),
    .ARADDR(s_axi_control_ARADDR),
    .RVALID(s_axi_control_RVALID),
    .RREADY(s_axi_control_RREADY),
    .RDATA(s_axi_control_RDATA),
    .RRESP(s_axi_control_RRESP),
    .BVALID(s_axi_control_BVALID),
    .BREADY(s_axi_control_BREADY),
    .BRESP(s_axi_control_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .Input_r(Input_r),
    .Output_r(Output_r),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_continue(ap_continue),
    .ap_idle(ap_idle)
);

Filter_HW_aximm1_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 16 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 69 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_AXIMM1_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_AXIMM1_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_AXIMM1_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_AXIMM1_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_AXIMM1_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_AXIMM1_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_AXIMM1_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_AXIMM1_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_AXIMM1_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_AXIMM1_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_AXIMM1_CACHE_VALUE ))
aximm1_m_axi_U(
    .AWVALID(m_axi_aximm1_AWVALID),
    .AWREADY(m_axi_aximm1_AWREADY),
    .AWADDR(m_axi_aximm1_AWADDR),
    .AWID(m_axi_aximm1_AWID),
    .AWLEN(m_axi_aximm1_AWLEN),
    .AWSIZE(m_axi_aximm1_AWSIZE),
    .AWBURST(m_axi_aximm1_AWBURST),
    .AWLOCK(m_axi_aximm1_AWLOCK),
    .AWCACHE(m_axi_aximm1_AWCACHE),
    .AWPROT(m_axi_aximm1_AWPROT),
    .AWQOS(m_axi_aximm1_AWQOS),
    .AWREGION(m_axi_aximm1_AWREGION),
    .AWUSER(m_axi_aximm1_AWUSER),
    .WVALID(m_axi_aximm1_WVALID),
    .WREADY(m_axi_aximm1_WREADY),
    .WDATA(m_axi_aximm1_WDATA),
    .WSTRB(m_axi_aximm1_WSTRB),
    .WLAST(m_axi_aximm1_WLAST),
    .WID(m_axi_aximm1_WID),
    .WUSER(m_axi_aximm1_WUSER),
    .ARVALID(m_axi_aximm1_ARVALID),
    .ARREADY(m_axi_aximm1_ARREADY),
    .ARADDR(m_axi_aximm1_ARADDR),
    .ARID(m_axi_aximm1_ARID),
    .ARLEN(m_axi_aximm1_ARLEN),
    .ARSIZE(m_axi_aximm1_ARSIZE),
    .ARBURST(m_axi_aximm1_ARBURST),
    .ARLOCK(m_axi_aximm1_ARLOCK),
    .ARCACHE(m_axi_aximm1_ARCACHE),
    .ARPROT(m_axi_aximm1_ARPROT),
    .ARQOS(m_axi_aximm1_ARQOS),
    .ARREGION(m_axi_aximm1_ARREGION),
    .ARUSER(m_axi_aximm1_ARUSER),
    .RVALID(m_axi_aximm1_RVALID),
    .RREADY(m_axi_aximm1_RREADY),
    .RDATA(m_axi_aximm1_RDATA),
    .RLAST(m_axi_aximm1_RLAST),
    .RID(m_axi_aximm1_RID),
    .RUSER(m_axi_aximm1_RUSER),
    .RRESP(m_axi_aximm1_RRESP),
    .BVALID(m_axi_aximm1_BVALID),
    .BREADY(m_axi_aximm1_BREADY),
    .BRESP(m_axi_aximm1_BRESP),
    .BID(m_axi_aximm1_BID),
    .BUSER(m_axi_aximm1_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(Filter_horizontal_HW3_U0_m_axi_aximm1_ARVALID),
    .I_ARREADY(aximm1_ARREADY),
    .I_ARADDR(Filter_horizontal_HW3_U0_m_axi_aximm1_ARADDR),
    .I_ARID(Filter_horizontal_HW3_U0_m_axi_aximm1_ARID),
    .I_ARLEN(Filter_horizontal_HW3_U0_m_axi_aximm1_ARLEN),
    .I_ARSIZE(Filter_horizontal_HW3_U0_m_axi_aximm1_ARSIZE),
    .I_ARLOCK(Filter_horizontal_HW3_U0_m_axi_aximm1_ARLOCK),
    .I_ARCACHE(Filter_horizontal_HW3_U0_m_axi_aximm1_ARCACHE),
    .I_ARQOS(Filter_horizontal_HW3_U0_m_axi_aximm1_ARQOS),
    .I_ARPROT(Filter_horizontal_HW3_U0_m_axi_aximm1_ARPROT),
    .I_ARUSER(Filter_horizontal_HW3_U0_m_axi_aximm1_ARUSER),
    .I_ARBURST(Filter_horizontal_HW3_U0_m_axi_aximm1_ARBURST),
    .I_ARREGION(Filter_horizontal_HW3_U0_m_axi_aximm1_ARREGION),
    .I_RVALID(aximm1_RVALID),
    .I_RREADY(Filter_horizontal_HW3_U0_m_axi_aximm1_RREADY),
    .I_RDATA(aximm1_RDATA),
    .I_RID(aximm1_RID),
    .I_RUSER(aximm1_RUSER),
    .I_RRESP(aximm1_RRESP),
    .I_RLAST(aximm1_RLAST),
    .I_AWVALID(1'b0),
    .I_AWREADY(aximm1_AWREADY),
    .I_AWADDR(64'd0),
    .I_AWID(1'd0),
    .I_AWLEN(32'd0),
    .I_AWSIZE(3'd0),
    .I_AWLOCK(2'd0),
    .I_AWCACHE(4'd0),
    .I_AWQOS(4'd0),
    .I_AWPROT(3'd0),
    .I_AWUSER(1'd0),
    .I_AWBURST(2'd0),
    .I_AWREGION(4'd0),
    .I_WVALID(1'b0),
    .I_WREADY(aximm1_WREADY),
    .I_WDATA(16'd0),
    .I_WID(1'd0),
    .I_WUSER(1'd0),
    .I_WLAST(1'b0),
    .I_WSTRB(2'd0),
    .I_BVALID(aximm1_BVALID),
    .I_BREADY(1'b0),
    .I_BRESP(aximm1_BRESP),
    .I_BID(aximm1_BID),
    .I_BUSER(aximm1_BUSER)
);

Filter_HW_aximm2_m_axi #(
    .CONSERVATIVE( 0 ),
    .USER_DW( 16 ),
    .USER_AW( 64 ),
    .USER_MAXREQS( 69 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_AXIMM2_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_AXIMM2_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_AXIMM2_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_AXIMM2_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_AXIMM2_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_AXIMM2_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_AXIMM2_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_AXIMM2_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_AXIMM2_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_AXIMM2_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_AXIMM2_CACHE_VALUE ))
aximm2_m_axi_U(
    .AWVALID(m_axi_aximm2_AWVALID),
    .AWREADY(m_axi_aximm2_AWREADY),
    .AWADDR(m_axi_aximm2_AWADDR),
    .AWID(m_axi_aximm2_AWID),
    .AWLEN(m_axi_aximm2_AWLEN),
    .AWSIZE(m_axi_aximm2_AWSIZE),
    .AWBURST(m_axi_aximm2_AWBURST),
    .AWLOCK(m_axi_aximm2_AWLOCK),
    .AWCACHE(m_axi_aximm2_AWCACHE),
    .AWPROT(m_axi_aximm2_AWPROT),
    .AWQOS(m_axi_aximm2_AWQOS),
    .AWREGION(m_axi_aximm2_AWREGION),
    .AWUSER(m_axi_aximm2_AWUSER),
    .WVALID(m_axi_aximm2_WVALID),
    .WREADY(m_axi_aximm2_WREADY),
    .WDATA(m_axi_aximm2_WDATA),
    .WSTRB(m_axi_aximm2_WSTRB),
    .WLAST(m_axi_aximm2_WLAST),
    .WID(m_axi_aximm2_WID),
    .WUSER(m_axi_aximm2_WUSER),
    .ARVALID(m_axi_aximm2_ARVALID),
    .ARREADY(m_axi_aximm2_ARREADY),
    .ARADDR(m_axi_aximm2_ARADDR),
    .ARID(m_axi_aximm2_ARID),
    .ARLEN(m_axi_aximm2_ARLEN),
    .ARSIZE(m_axi_aximm2_ARSIZE),
    .ARBURST(m_axi_aximm2_ARBURST),
    .ARLOCK(m_axi_aximm2_ARLOCK),
    .ARCACHE(m_axi_aximm2_ARCACHE),
    .ARPROT(m_axi_aximm2_ARPROT),
    .ARQOS(m_axi_aximm2_ARQOS),
    .ARREGION(m_axi_aximm2_ARREGION),
    .ARUSER(m_axi_aximm2_ARUSER),
    .RVALID(m_axi_aximm2_RVALID),
    .RREADY(m_axi_aximm2_RREADY),
    .RDATA(m_axi_aximm2_RDATA),
    .RLAST(m_axi_aximm2_RLAST),
    .RID(m_axi_aximm2_RID),
    .RUSER(m_axi_aximm2_RUSER),
    .RRESP(m_axi_aximm2_RRESP),
    .BVALID(m_axi_aximm2_BVALID),
    .BREADY(m_axi_aximm2_BREADY),
    .BRESP(m_axi_aximm2_BRESP),
    .BID(m_axi_aximm2_BID),
    .BUSER(m_axi_aximm2_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_ARVALID(1'b0),
    .I_ARREADY(aximm2_ARREADY),
    .I_ARADDR(64'd0),
    .I_ARID(1'd0),
    .I_ARLEN(32'd0),
    .I_ARSIZE(3'd0),
    .I_ARLOCK(2'd0),
    .I_ARCACHE(4'd0),
    .I_ARQOS(4'd0),
    .I_ARPROT(3'd0),
    .I_ARUSER(1'd0),
    .I_ARBURST(2'd0),
    .I_ARREGION(4'd0),
    .I_RVALID(aximm2_RVALID),
    .I_RREADY(1'b0),
    .I_RDATA(aximm2_RDATA),
    .I_RID(aximm2_RID),
    .I_RUSER(aximm2_RUSER),
    .I_RRESP(aximm2_RRESP),
    .I_RLAST(aximm2_RLAST),
    .I_AWVALID(Filter_vertical_HW_U0_m_axi_aximm2_AWVALID),
    .I_AWREADY(aximm2_AWREADY),
    .I_AWADDR(Filter_vertical_HW_U0_m_axi_aximm2_AWADDR),
    .I_AWID(Filter_vertical_HW_U0_m_axi_aximm2_AWID),
    .I_AWLEN(Filter_vertical_HW_U0_m_axi_aximm2_AWLEN),
    .I_AWSIZE(Filter_vertical_HW_U0_m_axi_aximm2_AWSIZE),
    .I_AWLOCK(Filter_vertical_HW_U0_m_axi_aximm2_AWLOCK),
    .I_AWCACHE(Filter_vertical_HW_U0_m_axi_aximm2_AWCACHE),
    .I_AWQOS(Filter_vertical_HW_U0_m_axi_aximm2_AWQOS),
    .I_AWPROT(Filter_vertical_HW_U0_m_axi_aximm2_AWPROT),
    .I_AWUSER(Filter_vertical_HW_U0_m_axi_aximm2_AWUSER),
    .I_AWBURST(Filter_vertical_HW_U0_m_axi_aximm2_AWBURST),
    .I_AWREGION(Filter_vertical_HW_U0_m_axi_aximm2_AWREGION),
    .I_WVALID(Filter_vertical_HW_U0_m_axi_aximm2_WVALID),
    .I_WREADY(aximm2_WREADY),
    .I_WDATA(Filter_vertical_HW_U0_m_axi_aximm2_WDATA),
    .I_WID(Filter_vertical_HW_U0_m_axi_aximm2_WID),
    .I_WUSER(Filter_vertical_HW_U0_m_axi_aximm2_WUSER),
    .I_WLAST(Filter_vertical_HW_U0_m_axi_aximm2_WLAST),
    .I_WSTRB(Filter_vertical_HW_U0_m_axi_aximm2_WSTRB),
    .I_BVALID(aximm2_BVALID),
    .I_BREADY(Filter_vertical_HW_U0_m_axi_aximm2_BREADY),
    .I_BRESP(aximm2_BRESP),
    .I_BID(aximm2_BID),
    .I_BUSER(aximm2_BUSER)
);

Filter_HW_Filter_horizontal_HW3 Filter_horizontal_HW3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Filter_horizontal_HW3_U0_ap_start),
    .start_full_n(start_for_Filter_vertical_HW_U0_full_n),
    .ap_done(Filter_horizontal_HW3_U0_ap_done),
    .ap_continue(Filter_horizontal_HW3_U0_ap_continue),
    .ap_idle(Filter_horizontal_HW3_U0_ap_idle),
    .ap_ready(Filter_horizontal_HW3_U0_ap_ready),
    .start_out(Filter_horizontal_HW3_U0_start_out),
    .start_write(Filter_horizontal_HW3_U0_start_write),
    .m_axi_aximm1_AWVALID(Filter_horizontal_HW3_U0_m_axi_aximm1_AWVALID),
    .m_axi_aximm1_AWREADY(1'b0),
    .m_axi_aximm1_AWADDR(Filter_horizontal_HW3_U0_m_axi_aximm1_AWADDR),
    .m_axi_aximm1_AWID(Filter_horizontal_HW3_U0_m_axi_aximm1_AWID),
    .m_axi_aximm1_AWLEN(Filter_horizontal_HW3_U0_m_axi_aximm1_AWLEN),
    .m_axi_aximm1_AWSIZE(Filter_horizontal_HW3_U0_m_axi_aximm1_AWSIZE),
    .m_axi_aximm1_AWBURST(Filter_horizontal_HW3_U0_m_axi_aximm1_AWBURST),
    .m_axi_aximm1_AWLOCK(Filter_horizontal_HW3_U0_m_axi_aximm1_AWLOCK),
    .m_axi_aximm1_AWCACHE(Filter_horizontal_HW3_U0_m_axi_aximm1_AWCACHE),
    .m_axi_aximm1_AWPROT(Filter_horizontal_HW3_U0_m_axi_aximm1_AWPROT),
    .m_axi_aximm1_AWQOS(Filter_horizontal_HW3_U0_m_axi_aximm1_AWQOS),
    .m_axi_aximm1_AWREGION(Filter_horizontal_HW3_U0_m_axi_aximm1_AWREGION),
    .m_axi_aximm1_AWUSER(Filter_horizontal_HW3_U0_m_axi_aximm1_AWUSER),
    .m_axi_aximm1_WVALID(Filter_horizontal_HW3_U0_m_axi_aximm1_WVALID),
    .m_axi_aximm1_WREADY(1'b0),
    .m_axi_aximm1_WDATA(Filter_horizontal_HW3_U0_m_axi_aximm1_WDATA),
    .m_axi_aximm1_WSTRB(Filter_horizontal_HW3_U0_m_axi_aximm1_WSTRB),
    .m_axi_aximm1_WLAST(Filter_horizontal_HW3_U0_m_axi_aximm1_WLAST),
    .m_axi_aximm1_WID(Filter_horizontal_HW3_U0_m_axi_aximm1_WID),
    .m_axi_aximm1_WUSER(Filter_horizontal_HW3_U0_m_axi_aximm1_WUSER),
    .m_axi_aximm1_ARVALID(Filter_horizontal_HW3_U0_m_axi_aximm1_ARVALID),
    .m_axi_aximm1_ARREADY(aximm1_ARREADY),
    .m_axi_aximm1_ARADDR(Filter_horizontal_HW3_U0_m_axi_aximm1_ARADDR),
    .m_axi_aximm1_ARID(Filter_horizontal_HW3_U0_m_axi_aximm1_ARID),
    .m_axi_aximm1_ARLEN(Filter_horizontal_HW3_U0_m_axi_aximm1_ARLEN),
    .m_axi_aximm1_ARSIZE(Filter_horizontal_HW3_U0_m_axi_aximm1_ARSIZE),
    .m_axi_aximm1_ARBURST(Filter_horizontal_HW3_U0_m_axi_aximm1_ARBURST),
    .m_axi_aximm1_ARLOCK(Filter_horizontal_HW3_U0_m_axi_aximm1_ARLOCK),
    .m_axi_aximm1_ARCACHE(Filter_horizontal_HW3_U0_m_axi_aximm1_ARCACHE),
    .m_axi_aximm1_ARPROT(Filter_horizontal_HW3_U0_m_axi_aximm1_ARPROT),
    .m_axi_aximm1_ARQOS(Filter_horizontal_HW3_U0_m_axi_aximm1_ARQOS),
    .m_axi_aximm1_ARREGION(Filter_horizontal_HW3_U0_m_axi_aximm1_ARREGION),
    .m_axi_aximm1_ARUSER(Filter_horizontal_HW3_U0_m_axi_aximm1_ARUSER),
    .m_axi_aximm1_RVALID(aximm1_RVALID),
    .m_axi_aximm1_RREADY(Filter_horizontal_HW3_U0_m_axi_aximm1_RREADY),
    .m_axi_aximm1_RDATA(aximm1_RDATA),
    .m_axi_aximm1_RLAST(aximm1_RLAST),
    .m_axi_aximm1_RID(aximm1_RID),
    .m_axi_aximm1_RUSER(aximm1_RUSER),
    .m_axi_aximm1_RRESP(aximm1_RRESP),
    .m_axi_aximm1_BVALID(1'b0),
    .m_axi_aximm1_BREADY(Filter_horizontal_HW3_U0_m_axi_aximm1_BREADY),
    .m_axi_aximm1_BRESP(2'd0),
    .m_axi_aximm1_BID(1'd0),
    .m_axi_aximm1_BUSER(1'd0),
    .Input_r(Input_r),
    .Output_r(Output_r),
    .Output_out_din(Filter_horizontal_HW3_U0_Output_out_din),
    .Output_out_full_n(Output_c_full_n),
    .Output_out_write(Filter_horizontal_HW3_U0_Output_out_write),
    .tempStream_din(Filter_horizontal_HW3_U0_tempStream_din),
    .tempStream_full_n(tempStream_full_n),
    .tempStream_write(Filter_horizontal_HW3_U0_tempStream_write)
);

Filter_HW_Filter_vertical_HW Filter_vertical_HW_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Filter_vertical_HW_U0_ap_start),
    .ap_done(Filter_vertical_HW_U0_ap_done),
    .ap_continue(Filter_vertical_HW_U0_ap_continue),
    .ap_idle(Filter_vertical_HW_U0_ap_idle),
    .ap_ready(Filter_vertical_HW_U0_ap_ready),
    .m_axi_aximm2_AWVALID(Filter_vertical_HW_U0_m_axi_aximm2_AWVALID),
    .m_axi_aximm2_AWREADY(aximm2_AWREADY),
    .m_axi_aximm2_AWADDR(Filter_vertical_HW_U0_m_axi_aximm2_AWADDR),
    .m_axi_aximm2_AWID(Filter_vertical_HW_U0_m_axi_aximm2_AWID),
    .m_axi_aximm2_AWLEN(Filter_vertical_HW_U0_m_axi_aximm2_AWLEN),
    .m_axi_aximm2_AWSIZE(Filter_vertical_HW_U0_m_axi_aximm2_AWSIZE),
    .m_axi_aximm2_AWBURST(Filter_vertical_HW_U0_m_axi_aximm2_AWBURST),
    .m_axi_aximm2_AWLOCK(Filter_vertical_HW_U0_m_axi_aximm2_AWLOCK),
    .m_axi_aximm2_AWCACHE(Filter_vertical_HW_U0_m_axi_aximm2_AWCACHE),
    .m_axi_aximm2_AWPROT(Filter_vertical_HW_U0_m_axi_aximm2_AWPROT),
    .m_axi_aximm2_AWQOS(Filter_vertical_HW_U0_m_axi_aximm2_AWQOS),
    .m_axi_aximm2_AWREGION(Filter_vertical_HW_U0_m_axi_aximm2_AWREGION),
    .m_axi_aximm2_AWUSER(Filter_vertical_HW_U0_m_axi_aximm2_AWUSER),
    .m_axi_aximm2_WVALID(Filter_vertical_HW_U0_m_axi_aximm2_WVALID),
    .m_axi_aximm2_WREADY(aximm2_WREADY),
    .m_axi_aximm2_WDATA(Filter_vertical_HW_U0_m_axi_aximm2_WDATA),
    .m_axi_aximm2_WSTRB(Filter_vertical_HW_U0_m_axi_aximm2_WSTRB),
    .m_axi_aximm2_WLAST(Filter_vertical_HW_U0_m_axi_aximm2_WLAST),
    .m_axi_aximm2_WID(Filter_vertical_HW_U0_m_axi_aximm2_WID),
    .m_axi_aximm2_WUSER(Filter_vertical_HW_U0_m_axi_aximm2_WUSER),
    .m_axi_aximm2_ARVALID(Filter_vertical_HW_U0_m_axi_aximm2_ARVALID),
    .m_axi_aximm2_ARREADY(1'b0),
    .m_axi_aximm2_ARADDR(Filter_vertical_HW_U0_m_axi_aximm2_ARADDR),
    .m_axi_aximm2_ARID(Filter_vertical_HW_U0_m_axi_aximm2_ARID),
    .m_axi_aximm2_ARLEN(Filter_vertical_HW_U0_m_axi_aximm2_ARLEN),
    .m_axi_aximm2_ARSIZE(Filter_vertical_HW_U0_m_axi_aximm2_ARSIZE),
    .m_axi_aximm2_ARBURST(Filter_vertical_HW_U0_m_axi_aximm2_ARBURST),
    .m_axi_aximm2_ARLOCK(Filter_vertical_HW_U0_m_axi_aximm2_ARLOCK),
    .m_axi_aximm2_ARCACHE(Filter_vertical_HW_U0_m_axi_aximm2_ARCACHE),
    .m_axi_aximm2_ARPROT(Filter_vertical_HW_U0_m_axi_aximm2_ARPROT),
    .m_axi_aximm2_ARQOS(Filter_vertical_HW_U0_m_axi_aximm2_ARQOS),
    .m_axi_aximm2_ARREGION(Filter_vertical_HW_U0_m_axi_aximm2_ARREGION),
    .m_axi_aximm2_ARUSER(Filter_vertical_HW_U0_m_axi_aximm2_ARUSER),
    .m_axi_aximm2_RVALID(1'b0),
    .m_axi_aximm2_RREADY(Filter_vertical_HW_U0_m_axi_aximm2_RREADY),
    .m_axi_aximm2_RDATA(16'd0),
    .m_axi_aximm2_RLAST(1'b0),
    .m_axi_aximm2_RID(1'd0),
    .m_axi_aximm2_RUSER(1'd0),
    .m_axi_aximm2_RRESP(2'd0),
    .m_axi_aximm2_BVALID(aximm2_BVALID),
    .m_axi_aximm2_BREADY(Filter_vertical_HW_U0_m_axi_aximm2_BREADY),
    .m_axi_aximm2_BRESP(aximm2_BRESP),
    .m_axi_aximm2_BID(aximm2_BID),
    .m_axi_aximm2_BUSER(aximm2_BUSER),
    .Output_r_dout(Output_c_dout),
    .Output_r_empty_n(Output_c_empty_n),
    .Output_r_read(Filter_vertical_HW_U0_Output_r_read),
    .tempStream_dout(tempStream_dout),
    .tempStream_empty_n(tempStream_empty_n),
    .tempStream_read(Filter_vertical_HW_U0_tempStream_read)
);

Filter_HW_fifo_w64_d2_S Output_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Filter_horizontal_HW3_U0_Output_out_din),
    .if_full_n(Output_c_full_n),
    .if_write(Filter_horizontal_HW3_U0_Output_out_write),
    .if_dout(Output_c_dout),
    .if_empty_n(Output_c_empty_n),
    .if_read(Filter_vertical_HW_U0_Output_r_read)
);

Filter_HW_fifo_w8_d2_S tempStream_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Filter_horizontal_HW3_U0_tempStream_din),
    .if_full_n(tempStream_full_n),
    .if_write(Filter_horizontal_HW3_U0_tempStream_write),
    .if_dout(tempStream_dout),
    .if_empty_n(tempStream_empty_n),
    .if_read(Filter_vertical_HW_U0_tempStream_read)
);

Filter_HW_start_for_Filter_vertical_HW_U0 start_for_Filter_vertical_HW_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Filter_vertical_HW_U0_din),
    .if_full_n(start_for_Filter_vertical_HW_U0_full_n),
    .if_write(Filter_horizontal_HW3_U0_start_write),
    .if_dout(start_for_Filter_vertical_HW_U0_dout),
    .if_empty_n(start_for_Filter_vertical_HW_U0_empty_n),
    .if_read(Filter_vertical_HW_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    ap_rst_n_inv <= ap_rst_reg_1;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_1 <= ap_rst_reg_2;
end

always @ (posedge ap_clk) begin
    ap_rst_reg_2 <= ~ap_rst_n;
end

assign Filter_horizontal_HW3_U0_ap_continue = 1'b1;

assign Filter_horizontal_HW3_U0_ap_start = ap_start;

assign Filter_vertical_HW_U0_ap_continue = ap_continue;

assign Filter_vertical_HW_U0_ap_start = start_for_Filter_vertical_HW_U0_empty_n;

assign Filter_vertical_HW_U0_start_full_n = 1'b1;

assign Filter_vertical_HW_U0_start_write = 1'b0;

assign ap_done = Filter_vertical_HW_U0_ap_done;

assign ap_idle = (Filter_vertical_HW_U0_ap_idle & Filter_horizontal_HW3_U0_ap_idle);

assign ap_ready = Filter_horizontal_HW3_U0_ap_ready;

assign ap_sync_continue = ap_continue;

assign ap_sync_done = Filter_vertical_HW_U0_ap_done;

assign ap_sync_ready = Filter_horizontal_HW3_U0_ap_ready;

assign start_for_Filter_vertical_HW_U0_din = 1'b1;

endmodule //Filter_HW
