# This file was automatically generated by Vpl
if { ![info exists _is_init_cmds] } {
  set vivado_error_file vivado_error.txt
  set vivado_warn_file vivado_warning.txt

  source ../../../.local/ocl_util.tcl
  source ../../../.local/platform.tcl
  namespace import ocl_util::*

  set _is_init_cmds true
}

source ../../../.local/debug_profile_hooks.tcl


# generate cookie file for messaging
write_cookie_file_impl "Filter_HW"

# utilization reports
report_utilization_impl true "Filter_HW" "routed" "" "../../../input" "../../../output"

# kernel service update
update_kernel_info ../../../../../link.steps.log /mnt/castor/seas_home/c/chihan/chihan/ese532_hw7/hw7/_x/link/int

# update noc node information
update_profile_metadata_postroute /mnt/castor/seas_home/c/chihan/chihan/ese532_hw7/hw7/_x/link/int
